# Generated by Django 4.2 on 2023-05-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0067_alter_db_fees_amount_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_txt_sms',
            field=models.BooleanField(default=True),
        ),
    ]
