# Generated by Django 4.2 on 2023-05-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0068_customuser_is_txt_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_whats_app_sms',
            field=models.BooleanField(default=True),
        ),
    ]
