# Generated by Django 4.2 on 2023-05-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0075_db_result_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_valid_up_to',
            field=models.DateTimeField(null=True),
        ),
    ]
